language: php

sudo: required
dist: precise

php:
  - 5.5
  - 5.6
  - 7.0

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - vendor
    - $HOME/.ccache
    - $HOME/.composer/cache

env:
  matrix:
    - PHALCON_VERSION="3.0.x"
    - PHALCON_VERSION="v3.0.1"

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update -q
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  - git clone --depth=1 --branch=${PHALCON_VERSION} https://github.com/phalcon/cphalcon.git

install:
  - (cd cphalcon/build; bash install &>/dev/null)
  - phpenv config-add ./tests/_ci/phalcon.ini &> /dev/null
  - php --ri phalcon

script:
  - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

addons:
  apt:
    packages:
      - gdb
      - re2c

notifications:
  email:
    recipients:
      - build@phalconphp.com
    on_success: change
    on_failure: always
